# -*- coding: utf-8 -*-
"""finance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oT4qK9IH8s_fSwf0uP9f1nnHxOB22Qh_
"""

import yfinance as yf
import pandas as pd

data = {
    'Ticker': ['PETR4.SA', 'VALE3.SA', 'ITUB4.SA'],
    'amount_shares': [100, 50, 200],
    'Buy_Price': [20.0, 30.0, 40.0]

}
portfolio = pd.DataFrame(data)
portfolio['Current_Price'] = portfolio['Ticker'].apply(lambda x: yf.Ticker(x).history(period='1d')['Close'].iloc[-1])
portfolio['Current_Value'] = portfolio['Current_Price'] * portfolio['amount_shares']
portfolio['Gain_Loss'] = (portfolio['Current_Value'] - (portfolio['amount_shares'] * portfolio['Buy_Price']))
total_value = portfolio['Current_Value'].sum()
portfolio = portfolio.round({'Current_Price': 2, 'Current_Value': 2, 'Gain_Loss': 2})
total_value = round(total_value, 2)


portfolio, total_value



import plotly.graph_objects as go

pie_colors = ['#3498db', '#e74c3c', '#2ecc71']
bar_colors = ['#f39c12', '#9b59b6', '#16a085']

fig_pie = go.Figure(go.Pie(labels=portfolio['Ticker'], values=portfolio['Current_Value'], hole=0.3, textinfo='percent+label', marker=dict(colors=pie_colors)))
fig_pie.update_layout(title="Portfolio Distribution", title_x=0.5, showlegend=True)

fig_bar = go.Figure(go.Bar(x=portfolio['Ticker'], y=portfolio['Gain_Loss'], marker=dict(color=portfolio['Gain_Loss'], colorscale='Viridis', showscale=True)))
fig_bar.update_layout(title="Gains/Losses per Stock", title_x=0.5, xaxis_title="Stock", yaxis_title="Gain/Loss (BRL)", showlegend=False)

fig_pie.show()
fig_bar.show()